.TH man 1 "$BUILD_DATE" "$PKG_VERSION" "$PKG_NAME"

.SH NAME
$PKG_NAME \- software development tool kit

.SH SYNOPSIS
magnus link
.br
magnus unlink

.SH DESCRIPTION
.B magnus
is software development tool kit for C, C++, Python. It is not a program, it
is meta package. It provides minimum environment for develop without effort
to install related packages and write config files. It contains two parts:
text editor and code executor.

Text editor is VIM, VIM's plugins and custom configuration. It provides the
way to edit code in console environment, all actions is perform by keyboard.
It towards to simplicity and efficiency. Text editor is describes in this man
page, see
.B TEXT EDITOR
section for detail.

Code executor is set of programs which use to create, debug and execute
program from source code. For more detail, see correspond man page of. 

.IP \[bu] 2
gcc
.IP \[bu]
python

.SH TEXT EDITOR

Text editor is VIM - Vi IMproved. To get basic knowledge about VIM, see 'man
vim'. VIM's plugins is not activated after installation because VIM
configuration is separate for users. To activate it, do by hands:

.RS 4
$ magnus link
.RE

After activate VIM's plugin, start VIM:

.RS 4
$ vim
.RE

Or disable VIM's plugin by.

.RS 4
$ magnus unlink
.RE

VIM loads plugins and configuration automatically. It is ready to uses,
immediately And there are additional features:

.IP \[bu] 2
Auto complete
.IP \[bu]
Auto open bracket
.IP \[bu]
Quick comment
.IP \[bu]
Create and remove session
.IP \[bu]
Auto save
.IP \[bu]
Quick open and close tab
.IP \[bu]
Quick compile
.IP \[bu]
Quick run command

.SH FILES
.B
/usr/share/magnus/
.br
Library directory.

.B
/home/$USER/.vimrc
.br
VIM configuration file when mangus is enable for $USER.

.SH REFERENCES
.B magnus's repository 
.br
https://github.com/kevin-leptons/magnus.

.SH BUGS
N/A

.SH AUTHOR
Kevin Leptons <kevin.leptons@gmail.com>
